const common = require("./common.js");

const PROFILE = "dockerignore";
const ATTRIBUTION =
  "# === Autogenerated by CompactIgnore::dockerignore === #\n\n";

async function build(obj) {
  let use = common.getGenericProfiles(obj);

  if (obj["dockerignore"]) {
    use = use.concat(obj["dockerignore"].children);
  }

  let tempContent = await generateContent(use);

  let file = {
    name: ".dockerignore",
    content: tempContent,
    attribution: ATTRIBUTION,
  };

  return file;
}

async function generateContent(obj) {
  let content = "";

  for (let i = 0; i < obj.length; i++) {
    if (obj[i].type === "comment") {
      content += `# ${obj[i].value}\n`;
    }
    if (obj[i].type === "inclusion") {
      content += `!${obj[i].value}\n`;
    }
    if (obj[i].type === "exclusion") {
      content += `${obj[i].value}\n`;
    }
  }

  return content;
}

module.exports = {
  PROFILE,
  build,
};
