function injest(data) {
  var tmpReturn = "";

  if (isNotNull(data.comment)) {
    tmpReturn += addComment(data.comment);
  }

  if (isNotNull(data.action) && isNotNull(data.location)) {
    tmpReturn += addEntry(data.action, data.location);
  }

  return tmpReturn;
}

function addComment(string) {
  let comment = sanatize(string);
  comment = `# ${comment}\n`;
  return comment;
}

function addEntry(action, location) {
  let fileLoc = sanatize(location);
  var tmpReturn = "";

  if (action == "exclude") {
    tmpReturn = `${fileLoc}\n`;
  } else if (action == "include") {
    tmpReturn = `!${fileLoc}\n`;
  }
  return tmpReturn;
}

function attribution() {
  return "# === This file was Autogenerated by the CompactIgnore dockerignore Profile === #\n\n";
}

function isNotNull(toCheck) {
  return typeof toCheck !== null;
}

function sanatize(string) {
  let sanatizeString = string.replace("\r", "").replace("\n", "");
  sanatizeString = sanatizeString.trim();
  return sanatizeString;
}

module.exports = { injest, attribution };
