const {
  isNotNull,
  gitLikeAddComment,
  gitLikeAddEntryNoEscape,
} = require("./helpers.js");

function injest(data) {
  var tmpReturn = "";

  if (isNotNull(data.comment)) {
    tmpReturn += gitLikeAddComment(data.comment);
  }

  if (isNotNull(data.action) && isNotNull(data.location)) {
    tmpReturn += gitLikeAddEntryNoEscape(data.action, data.location);
  }

  return tmpReturn;
}

function attribution() {
  return "# === This file was Autogenerated by the CompactIgnore dockerignore Profile === #\n\n";
}

module.exports = { injest, attribution };
