// The Gitignore Parser will take an entry in and return a valid .gitignore entry, consisting of only the file directive, or may put an associated comment before it.
// This file will escape any characters as needed, but will not remove or operate on pre-escaped characters.
// Attempting to leave all the benifits of the .gitignore format available with use of the parser.

const {
  isNotNull,
  gitLikeAddComment,
  gitLikeAddEntryEscape,
} = require("./helpers.js");

function injest(data) {
  var tmpReturn = "";

  if (isNotNull(data.comment)) {
    tmpReturn += gitLikeAddComment(data.comment);
  }

  if (isNotNull(data.action) && isNotNull(data.location)) {
    tmpReturn += gitLikeAddEntryEscape(data.action, data.location);
  }
  return tmpReturn;
}

function attribution() {
  return "# === This file was Autogenerated by the CompactIgnore gitignore Profile === #\n\n";
}

module.exports = { injest, attribution };
