const {
  isNotNull,
  gitLikeAddComment,
  gitLikeAddEntryEscape,
  gitLikeInjest,
} = require("./helpers.js");

function injest(data) {
  return gitLikeInjest(data, true);
}

function attribution() {
  return "# === This file was Autogenerated by the CompactIgnore npmignore Profile === #\n\n";
}

module.exports = { injest, attribution };
