const { gitLikeInjest } = require("./helpers.js");

function injest(data) {
  return gitLikeInjest(data, true);
}

function attribution() {
  return "# === This file was Autogenerated by the CompactIgnore prettierignore Profile === #\n\n";
}

module.exports = { injest, attribution };
