const { isNotNull, sanatize } = require("./helpers.js");

function injest(data) {
  var tmpReturn = "";

  if (isNotNull(data.comment)) {
    tmpReturn += addComment(data.comment);
  }

  if (isNotNull(data.action) && isNotNull(data.location)) {
    tmpReturn += addEntry(data.action, data.location);
  }
  return tmpReturn;
}

function addComment(string) {
  let comment = sanatize(string);
  comment = `# ${comment}\n`;
  return comment;
}

function addEntry(action, location) {
  let fileLoc = sanatize(location);
  let formattedLoc = escape(fileLoc);
  var tmpReturn = "";

  if (action == "exclude") {
    tmpReturn = `${formattedLoc}\n`;
  } else if (action == "include") {
    tmpReturn = `!${formattedLoc}`;
  }
  return tmpReturn;
}

function attribution() {
  return "# === This file was Autogenerated by the CompactIgnore prettierignore Profile === #\n\n";
}

function escape(string) {
  // this will take a sanatized file location string, and escape as needed, in line with the spec
  // Keeping in mind that this is used for actual entries and not comments.

  var escapedString = string;
  // Check starting with #
  if (escapedString.match(/^[#]/g) != null) {
    escapedString = `\\${escapedString}`;
  }
  // Check starting with !
  if (escapedString.match(/^[!]/g) != null) {
    escapedString = `\\${escapedString}`;
  }

  return escapedString;
}

module.exports = { injest, attribution };
